builders:
  mockalization_generator:
    import: "package:mockalization_generator/builder.dart"
    builder_factories: ["fakeGenerator"]
    build_extensions: {".dart": [".mockalization.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]